server:
  port: 8080
  servlet:
    session:
      timeout: 60
  tomcat:
    max-threads: 800
    accesslog:
      enabled: false
      pattern: '%{X-Forwarded-For}i %l %u [%{yyyy-MM-dd HH:mm:ss:mmm}t] "%r" %s %b %D "%{HTTP_X_UP_CALLING_LINE_ID}i" "%{x-up-calling-line-id}i" "%{User-Agent}i"'
      directory: /data/logs/learn/access


learn:
  temp-path: /data/app/learn/temp/

spring:
  profiles:
    # 为了接收系统变量, mvn -P {profile},
    active: @profileActive@
  application:
    name: learn
  jackson:
    serialization:
      write-dates-as-timestamps: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/**/*.xml



