server:
  port: 8080
  tomcat:
    accesslog:
      enabled: false
      pattern: '%{X-Forwarded-For}i %l %u [%{yyyy-MM-dd HH:mm:ss:mmm}t] "%r" %s %b %D "%{HTTP_X_UP_CALLING_LINE_ID}i" "%{x-up-calling-line-id}i" "%{User-Agent}i"'
      directory: /data/logs/learn/access
    mbeanregistry:
      enabled: true
    threads:
      max: 500

spring:
  profiles:
    # 为了接收系统变量, mvn -P {profile},
    active: @profileActive@
  application:
    name: learn-java
  jackson:
    serialization:
      write-dates-as-timestamps: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      app: ${spring.application.name}
#    distribution:
#      slo: # yaml的写法真的是奇怪, 这样写才可以映射为普通写法的http.server.requests
#        http:
#          server:
#            requests: 50ms,100ms,200ms,300ms,400ms,500ms

learn:
  temp-path: /data/app/learn/temp/


